services:
  redis:
    image: redis:8.0-alpine
    ports:
      - "6379:6379"
    container_name: "redis"    
    networks:
      - crawler_net

  crawler_app:
    build: .
    volumes:
      - ./src:/app/src
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_QUEUE_NAME=product_jobs
      - EITAA_API_KEY=eitaa_redis_key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    container_name: "crawler"
    networks:
      - crawler_net

networks:
  crawler_net: